---
title: "Data resources"
output: github_document
---

```{r setup0, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
library(here)
library(tidyverse)
library(data.table)
library(readxl)
library(ggnewscale)
knitr::opts_chunk$set(root.dir = here(), comment = NA, echo = FALSE, message = FALSE, warnings = FALSE, include = TRUE, fig.align = 'center', fig.path = "figures/")
source("scripts/utils.R")
```

### Public data

**1. Nones et al 2019**

This dataset composed of tumour/normal WGS data of 78 familial breast cancer patients. The clinical status of these samples are:

```{r prepare-table}
meta_data <- read_excel("data/Nones/Supplementary_Table1.xlsx",skip = 1, col_names = TRUE)
meta_data<- meta_data %>% add_column(BRCA_status=c(rep("BRCA1",26),rep("BRCA2",22), rep("non-BRCA",30))) %>% mutate(Morphology=`Morphology coding`)
meta_data$HER2 <- meta_data$HER2 %>% str_replace("NA","n/a")
meta_data$ER <- meta_data$ER %>% str_replace("NA","n/a")
meta_data$PR <- meta_data$PR %>% str_replace("NA","n/a")
meta_data$Grade <- meta_data$Grade %>% str_replace("NA","n/a")

meta_df<-meta_data %>% select(-c(`Age at diagnosis (years)`,`kConFab HGVS`,`Tumour Size (mm)`,`Morphology`)) %>%
  dplyr::rename("Morphology"=`Morphology coding`) %>% 
  pivot_longer(-Donor,names_to = "field",values_to = "level") 

meta_df$field <- factor(meta_df$field,levels = c("BRCA_status","Gender","Age Group","Grade","ER","PR","HER2","Morphology") %>% rev)
meta_df$Donor <- factor(meta_df$Donor,levels = meta_df$Donor %>% unique %>% rev)

meta_data$BRCA_status %>% table() %>% knitr::kable()
```


```{r fig1, fig.width=12}
plot1 <- ggplot() + 
  scale_y_discrete(limits=levels(meta_df$field)) +
  theme_minimal(base_size = 12)+
  theme(legend.position="bottom",
        legend.direction  = "vertical",
        panel.grid.major = element_blank(),
        axis.text.x = element_blank()) + 
  labs(x="",y="")


for (i in levels(meta_df$field)){
  if(i %in% c("HER2","PR","ER")){
    colors <- color_fig[["ER/PR/HER2"]]
    color_name <- "ER/PR/HER2"
  }else{
    colors <-color_fig[[i]]
    color_name <- legend_names[[i]]
  }
  plot1 <- plot1 + generate_row(i,meta_df) +
    scale_fill_manual(values = colors, name=color_name)+ 
    new_scale_fill()
}

plot1
```

**2. TCGA-BRCA WGS data**

This dataset was pulled down from TCGA GCD portal and is composed of 116 donors' data. The basic clinical information are:

```{r}
brca_somatic <- fread("data/TCGA/brca_somatic.txt",col.names = c("Donor","BRCA1","BRCA2"))
tcga <- read_tsv("data/TCGA/TCGA-BRCA_116.txt") %>% select(bcr_patient_barcode, gender,age_at_diagnosis,er_status_by_ihc, pr_status_by_ihc,her2_status_by_ihc,icd_o_3_histology) %>% 
  dplyr::rename("Donor"=bcr_patient_barcode, "ER"=er_status_by_ihc, "PR"= pr_status_by_ihc, "HER2"=her2_status_by_ihc,"icd_o_3"=icd_o_3_histology) %>% 
  mutate(age_group=case_when(age_at_diagnosis<40 ~ "<40",
                             age_at_diagnosis<50 ~"40-50",
                             age_at_diagnosis<60~"50-60",
                             age_at_diagnosis<70~"60-70",
                             TRUE~">70")) %>% 
  select(-age_at_diagnosis) %>% 
  mutate(ER=ifelse(ER%in% c("Positive","Negative"),ER,"n/a"),
         PR=ifelse(PR%in% c("Positive","Negative"),PR,"n/a"),
         HER2=ifelse(HER2%in% c("Positive","Negative"),HER2,"n/a")) %>% 
  full_join(brca_somatic) %>% 
  mutate(BRCA_status=case_when(BRCA1>0~"BRCA1",
                               BRCA2>0~"BRCA2",
                               TRUE~"non-BRCA")) %>% select(-c(BRCA1,BRCA2)) %>% 
  arrange(BRCA_status)

tcga$Donor <- factor(tcga$Donor, levels = rev(tcga$Donor))
tcga_df <- tcga %>% pivot_longer(-Donor,names_to = "field",values_to = "level")
tcga_df$field <- factor(tcga_df$field, levels = c("BRCA_status","gender","age_group","ER","PR","HER2","icd_o_3") %>% rev())
```

```{r fig2, fig.width=12}
plot2 <- ggplot() + 
  scale_y_discrete(limits=levels(tcga_df$field),labels=c("Morphology","HER2","PR","ER","Age group","Gender","BRCA somatic")) +
  theme_minimal(base_size = 12)+
  theme(legend.position="bottom",
        legend.direction  = "vertical",
        panel.grid.major = element_blank(),
        axis.text.x = element_blank()) + 
  labs(x="",y="")

for (i in levels(tcga_df$field)){
  if(i %in% c("HER2","PR","ER")){
    colors <- color_fig[["ER/PR/HER2"]]
    color_name <- "ER/PR/HER2"
  }else{
    colors <-color_fig[[i]]
    color_name <- legend_names[[i]]
  }
  plot2 <- plot2 + generate_row(i,tcga_df) +
    scale_fill_manual(values = colors, name=color_name)+ 
    new_scale_fill()
}

plot2
```

### Magic data

- The 157 WGS Tumor/normal paired data
- ~ 300 WES germline data

