---
title: "Substitution mutational signatures"
output: github_document
---

```{r setup0, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
library(here)
library(tidyverse)
library("BSgenome.Hsapiens.UCSC.hg19",character.only = TRUE)
library(MutationalPatterns)
library(NMF)
library(ccfindR)
library(ggsci)
knitr::opts_chunk$set(root.dir = here(), comment = NA, echo = FALSE, message = FALSE, warnings = FALSE, include = TRUE, fig.align = 'center', fig.path = "figures/")
hg19 <- BSgenome.Hsapiens.UCSC.hg19
chr_levels=c("1","2","3","4","5","6","7","8","9","10","11",
             "12","13","14","15","16","17","18","19","20","21",
             "22","X")
all_chr <- paste0("chr",chr_levels)

my_colors <- c("#FF7F0E","#2CA02A","#1F77B4","#D62728","#9467BD","grey","yellow","pink")
meta_data <- read_rds("meta_data.rds")
brca_status <- meta_data[match(sample_names,meta_data$Donor),c("Donor","BRCA_status")] %>% arrange(BRCA_status)
```

### de novo mutational signature extraction using NMF

```{r, warning=FALSE}
brca_samples <- brca_status %>% filter(BRCA_status!="non-BRCA") %>% pull(Donor)
vcf_files <- list.files("data/Nones/vcfs/snv", pattern = "*.snv.vcf", full.names = TRUE) 
sample_names <- basename(vcf_files) %>% str_remove(".snv.vcf")

names(vcf_files) <- sample_names

brca_vcf_files <- vcf_files[names(vcf_files)%in% brca_samples]

grl <- read_vcfs_as_granges(vcf_files, sample_names, hg19, predefined_dbs_mbs = TRUE)
brca_grl <-read_vcfs_as_granges(brca_vcf_files, brca_samples, hg19, predefined_dbs_mbs = TRUE)

grl <- grl[seqnames(grl) != "chrY", ] # remove SNVs from chrY because most patients are women.

mut_mat <- mut_matrix(grl, hg19) + 0.0001
```


To determine the number of mutational signatures to extract, we used two methods: NMF package and variational bayes NMF.

```{r}
## Bayes NMF estimate
sc <- scNMFSet(count = mut_mat)
set.seed(36)
estimate_bayes <- vb_factorize(sc, ranks = 1:8, nrun=1000)

## NMF estimate
estimate_nmf <- nmf(mut_mat, rank = 2:6, method = "brunet", seed=123456, nrun=10, .opt="v-p")
```


```{r}
plot(estimate_bayes)
plot(estimate_nmf) 
```

Seems like it is difficult to decide from 4 and 5. Thus I extracted 4 and 5 signatures separately.

```{r}
nmf_res4 <- extract_signatures(mut_mat, rank = 4, nrun = 200)
nmf_res5 <- extract_signatures(mut_mat, rank = 5, nrun = 200)

nmf_bayes_res <- extract_signatures(mut_mat2, rank = 5, nmf_type="variational_bayes")


cosmic2_h19 <- read_tsv("data/cosmic/COSMIC_v2_SBS_GRCh37.txt") %>%
  arrange(match(Type,rownames(mut_mat))) %>% 
  column_to_rownames("Type") %>% as.matrix


cosmic3_h19 <- read_tsv("data/cosmic/COSMIC_v3.3.1_SBS_GRCh37.txt") %>%
  arrange(match(Type,rownames(mut_mat))) %>% 
  column_to_rownames("Type") %>% as.matrix

```

```{r}
nmf_res4 <- rename_nmf_signatures(nmf_res4, cosmic2_h19 , cutoff = 0.80)
nmf_res5 <- rename_nmf_signatures(nmf_res5, cosmic2_h19 , cutoff = 0.80)

#BiocManager::install(c("BSgenome.Hsapiens.UCSC.hg38", "BSgenome.Hsapiens.1000genomes.hs37d5", "BSgenome.Mmusculus.UCSC.mm10", "BSgenome.Cfamiliaris.UCSC.canFam3", "NNLM", "nnls", "GenSA", "RCircos"))
```


```{r}
res4_df <- nmf_res4$contribution %>% as.data.frame() %>% rownames_to_column("sig") %>% 
  pivot_longer(-sig,names_to = "Donor",values_to = "contribution") %>% left_join(brca_status)

res4_df$sig <- factor(res4_df$sig, levels = rev(c("Signature 13-like","Signature 18-like","Signature 1-like","Signature 3-like")))
res4_df$BRCA_status <- factor(res4_df$BRCA_status, levels= c("non-BRCA","BRCA2","BRCA1"))

ggplot(res4_df, aes(x=Donor, y= contribution, fill=sig))+
  geom_bar(stat="identity",position = "fill") + 
  facet_wrap(~BRCA_status, scales = "free_x") + 
  scale_fill_manual(values = my_colors) +
  theme_bw(base_size = 12) + labs(x="",y="",fill="") +
  theme(axis.text.x = element_blank(),axis.ticks.x = element_blank(), 
        legend.position = "bottom",legend.margin =margin(0,0,0,0))

#ggsave("figures/fig-cosmic2-n4.png",width = 8.6, height = 3.4,dpi = 300)
```

```{r}

res5_df <- nmf_res5$contribution %>% as.data.frame() %>% rownames_to_column("sig") %>% 
  pivot_longer(-sig,names_to = "Donor",values_to = "contribution") %>% left_join(brca_status)

#res5_df$Donor <- factor(res5_df$Donor, levels = brca_status$Donor)
res5_df$sig <- factor(res5_df$sig, levels = rev(c("Signature 8-like","Signature 13-like","Signature 18-like","Signature 1-like","Signature 3-like")))
res5_df$BRCA_status <- factor(res5_df$BRCA_status, levels= c("non-BRCA","BRCA2","BRCA1"))

ggplot(res5_df, aes(x=Donor, y= contribution, fill=sig))+
  geom_bar(stat="identity",position = "fill") + 
  facet_wrap(~BRCA_status, scales = "free_x") + 
  scale_fill_manual(values = my_colors) +
  theme_bw(base_size = 12) + labs(x="",y="",fill="") +
  theme(axis.text.x = element_blank(),axis.ticks.x = element_blank(), 
        legend.position = "bottom",legend.margin =margin(0,0,0,0))

#ggsave("figures/fig-cosmic2-n5.png",width = 8.6, height = 3.4,dpi = 300)
```




```{r}
nmf_res4 <- rename_nmf_signatures(nmf_res4, cosmic3_h19 , cutoff = 0.70)
nmf_res5 <- rename_nmf_signatures(nmf_res5, cosmic3_h19 , cutoff = 0.70)

```


```{r}
res4_df <- nmf_res4$contribution %>% as.data.frame() %>% rownames_to_column("sig") %>% 
  pivot_longer(-sig,names_to = "Donor",values_to = "contribution") %>% left_join(brca_status)

res4_df$sig <- factor(res4_df$sig, levels = rev(c("SBS13-like","SBS18-like","SBS6-like","SBS3-like")))
res4_df$BRCA_status <- factor(res4_df$BRCA_status, levels= c("non-BRCA","BRCA2","BRCA1"))

ggplot(res4_df, aes(x=Donor, y= contribution, fill=sig))+
  geom_bar(stat="identity",position = "fill") + 
  facet_wrap(~BRCA_status, scales = "free_x") + 
  scale_fill_manual(values = my_colors) +
  theme_bw(base_size = 12) + labs(x="",y="",fill="") +
  theme(axis.text.x = element_blank(),axis.ticks.x = element_blank(), 
        legend.position = "bottom",legend.margin =margin(0,0,0,0))

#ggsave("figures/fig-cosmic3-n4.png",width = 8.6, height = 3.4,dpi = 300)
```

```{r}

res5_df <- nmf_res5$contribution %>% as.data.frame() %>% rownames_to_column("sig") %>% 
  pivot_longer(-sig,names_to = "Donor",values_to = "contribution") %>% left_join(brca_status)

#res5_df$Donor <- factor(res5_df$Donor, levels = brca_status$Donor)
res5_df$sig <- factor(res5_df$sig, levels = rev(c("SBS2-like","SBS40-like","SBS18-like","SBS1-like","SBS3-like")))
res5_df$BRCA_status <- factor(res5_df$BRCA_status, levels= c("non-BRCA","BRCA2","BRCA1"))

ggplot(res5_df, aes(x=Donor, y= contribution, fill=sig))+
  geom_bar(stat="identity",position = "fill") + 
  facet_wrap(~BRCA_status, scales = "free_x") + 
  scale_fill_manual(values = my_colors) +
  theme_bw(base_size = 12) + labs(x="",y="",fill="") +
  theme(axis.text.x = element_blank(),axis.ticks.x = element_blank(), 
        legend.position = "bottom",legend.margin =margin(0,0,0,0))

#ggsave("figures/fig-cosmic3-n5.png",width = 8.6, height = 3.4,dpi = 300)
```



