---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## BRCA1/2 germline variant curation based on tumour HRD.

Scripts and R code used in the paper:

[placeholder]

### Cohort and data resources

- [Data resources](1.data_summary.md) 
- [FFPE sample signature correction](FFPE_correction.md)

### Germline variants and BRCA1/2 classfication

- [Germline classification](6.germline_classification.md)

### HRD analysis

- [HRDsum score calculation](4.hrdsum_calculation.md)
- [HRD prediction using HRDetect](2.hrdetect.md)
- [HRD prediction using CHORD](3.chord.md)
- [HRD precition method comparison](5.hrdprediction_comparison.md)

As CHORD and HRD had consistently predicted tumours as HRD in most samples (except 5) and CHORD can further distinguish HRD samples in BRCA1 and BRCA2 types. The main LR ratio analysis was performed with CHORD results.

### `sessionInfo`

```
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats4    grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] colorspace_2.1-1                  ggmosaic_0.3.3                   
 [3] waffle_1.0.2                      BSgenome.Hsapiens.UCSC.hg38_1.4.5
 [5] BSgenome_1.72.0                   rtracklayer_1.64.0               
 [7] BiocIO_1.14.0                     Biostrings_2.72.1                
 [9] XVector_0.44.0                    GenomicRanges_1.56.1             
[11] GenomeInfoDb_1.40.1               IRanges_2.38.1                   
[13] S4Vectors_0.42.1                  BiocGenerics_0.50.0              
[15] CHORD_2.03                        signature.tools.lib_2.4.4        
[17] googlesheets4_1.1.1               RColorBrewer_1.1-3               
[19] vcfR_1.15.0                       data.table_1.15.4                
[21] ggthemes_5.1.0                    patchwork_1.2.0                  
[23] ggrepel_0.9.6                     ggalluvial_0.12.5                
[25] ggparty_1.0.0                     partykit_1.2-22                  
[27] mvtnorm_1.2-5                     libcoin_1.0-10                   
[29] gt_0.11.1                         ggh4x_0.2.8                      
[31] yaml_2.3.10                       here_1.0.1                       
[33] rpart.plot_3.1.2                  rpart_4.1.23                     
[35] lubridate_1.9.3                   forcats_1.0.0                    
[37] stringr_1.5.1                     dplyr_1.1.4                      
[39] purrr_1.0.2                       readr_2.1.5                      
[41] tidyr_1.3.1                       tibble_3.2.1                     
[43] ggplot2_3.5.1                     tidyverse_2.0.0                  

loaded via a namespace (and not attached):
  [1] rstudioapi_0.16.0           jsonlite_1.8.8              magrittr_2.0.3             
  [4] farver_2.1.2                rmarkdown_2.27              fs_1.6.4                   
  [7] zlibbioc_1.50.0             vctrs_0.6.5                 Rsamtools_2.20.0           
 [10] RCurl_1.98-1.16             rstatix_0.7.2               htmltools_0.5.8.1          
 [13] S4Arrays_1.4.1              curl_5.2.1                  broom_1.0.6                
 [16] cellranger_1.1.0            SparseArray_1.4.8           Formula_1.2-5              
 [19] htmlwidgets_1.6.4           plyr_1.8.9                  plotly_4.10.4              
 [22] GenomicAlignments_1.40.0    lifecycle_1.0.4             iterators_1.0.14           
 [25] pkgconfig_2.0.3             Matrix_1.7-0                R6_2.5.1                   
 [28] fastmap_1.2.0               GenomeInfoDbData_1.2.12     MatrixGenerics_1.16.0      
 [31] digest_0.6.36               rprojroot_2.0.4             ggpubr_0.6.0               
 [34] vegan_2.6-6.1               labeling_0.4.3              fansi_1.0.6                
 [37] timechange_0.3.0            httr_1.4.7                  abind_1.4-5                
 [40] mgcv_1.9-1                  compiler_4.4.1              gargle_1.5.2               
 [43] withr_3.0.1                 backports_1.5.0             BiocParallel_1.38.0        
 [46] carData_3.0-5               Rttf2pt1_1.3.12             ggsignif_0.6.4             
 [49] MASS_7.3-60.2               DelayedArray_0.30.1         rjson_0.2.21               
 [52] permute_0.9-7               tools_4.4.1                 googledrive_2.1.1          
 [55] ape_5.8                     extrafontdb_1.0             glue_1.8.0                 
 [58] restfulr_0.0.15             nlme_3.1-164                inum_1.0-5                 
 [61] rsconnect_1.3.1             checkmate_2.3.2             cluster_2.1.6              
 [64] generics_0.1.3              gtable_0.3.5                tzdb_0.4.0                 
 [67] pinfsc50_1.3.0              hms_1.1.3                   xml2_1.3.6                 
 [70] car_3.1-2                   utf8_1.2.4                  foreach_1.5.2              
 [73] pillar_1.9.0                splines_4.4.1               lattice_0.22-6             
 [76] survival_3.6-4              tidyselect_1.2.1            knitr_1.47                 
 [79] gridExtra_2.3               SummarizedExperiment_1.34.0 xfun_0.44                  
 [82] Biobase_2.64.0              matrixStats_1.3.0           DT_0.33                    
 [85] stringi_1.8.4               UCSC.utils_1.0.0            lazyeval_0.2.2             
 [88] evaluate_0.24.0             codetools_0.2-20            extrafont_0.19             
 [91] cli_3.6.3                   munsell_0.5.1               Rcpp_1.0.13                
 [94] XML_3.99-0.17               parallel_4.4.1              bitops_1.0-8               
 [97] viridisLite_0.4.2           scales_1.3.0                crayon_1.5.3               
[100] rlang_1.1.4 
```



